# -------------------------------------------------------------
# Test Server
# -------------------------------------------------------------
server.port=8080

# -------------------------------------------------------------
# Oracle Database Connection
# -------------------------------------------------------------
# Oracle TEST DB Connection
#spring.datasource.url={{Base_URL}}
#spring.datasource.username={{USERNAME}}
#spring.datasource.password={{PASSWORD}}

# Use modern Oracle driver class
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# -------------------------------------------------------------
# JPA
# -------------------------------------------------------------
# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.data.jdbc.repositories.enabled=false

