# -------------------------------------------------------------
# Production Server
# -------------------------------------------------------------
server.port=8080

# -------------------------------------------------------------
# Oracle Database Connection
# -------------------------------------------------------------
# Oracle Production DB Connection
spring.datasource.url=jdbc:oracle:thin:@10.4.1.25:1541/PROD
spring.datasource.username=apps
spring.datasource.password=sugapps

# Use modern Oracle driver class
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# -------------------------------------------------------------
# JPA
# -------------------------------------------------------------
# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.data.jdbc.repositories.enabled=false


